version: "3.9"
services:
  api:
    build: .
    ports: ["8080:8080"]
    environment: ["RUST_LOG=info"]
    depends_on: [db]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports: ["5432:5432"]
